name: reports

on: [pull_request]

jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
          - name: Quality Report
            id: quality-report
            uses: noh4nsen/quality-report@0c542be11f3cce4a8ba452e1c2548ed035f3eae7
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              head_branch: ${{ github.head_ref }}
              base_branch: ${{ github.base_ref }}