name: reports

on: [pull_request]

jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
          - name: Quality Report
            id: quality-report
            uses: noh4nsen/quality-report@ecff638eed22acf6a883d03b2d774a244124c07d
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              head_branch: ${{ github.head_ref }}
              base_branch: ${{ github.base_ref }}