name: reports

on:
  pull_request:

jobs:
    diff:
        runs-on: ubuntu-latest
        outputs:
          modified_projects: ${{ steps.go-diff.outputs.modified_projects }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Go-diff
            id: go-diff
            uses: noh4nsen/go-diff@1.4.0
            with:
              head_branch: ${{ github.head_ref }}
              base_branch: ${{ github.base_ref }}

    tflint:
        runs-on: ubuntu-latest
        outputs:
          tflint_report: ${{ steps.tflint-report.outputs.tflint_report }}
        needs: [diff]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: TFLint Report
            id: tflint-report
            uses: noh4nsen/tflint-report@a29b2d3dbfd24c7d28227a9cd04418b2468f1574
            with:
              modified_projects: ${{ needs.diff.outputs.modified_projects }}

    tfsec:
        runs-on: ubuntu-latest
        outputs:
          tfsec_report: ${{ steps.tfsec-report.outputs.tfsec_report }}
        needs: [diff]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Tfsec Report
            id: tfsec-report
            uses: noh4nsen/tfsec-report@96322e49d596fa9aa7cb2a57b467aaba05e92cc7
            with:
              modified_projects: ${{ needs.diff.outputs.modified_projects }}

    checkov:
        runs-on: ubuntu-latest
        outputs:
          checkov_report: ${{ steps.checkov-report.outputs.checkov_report }}
        needs: [diff]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Checkov Report
            id: checkov-report
            uses: noh4nsen/checkov-report@5841f2e504b1dfc17a267c66c72f487b2054a1ad
            with:
              modified_projects: ${{ needs.diff.outputs.modified_projects }}

    report:
        runs-on: ubuntu-latest
        needs: [tflint, tfsec, checkov]
        steps:
          - name: Quality Report Aggregator
            id: quality-report-aggregator
            uses: noh4nsen/quality-report-aggregator@1.4.0
            with:
              tflint_report: ${{ needs.tflint.outputs.tflint_report }}
              tfsec_report: ${{ needs.tfsec.outputs.tfsec_report }}
              checkov_report: ${{ needs.checkov.outputs.checkov_report }}
          - name: Comment Report
            uses: actions/github-script@v6
            env:
              REPORT: "${{ steps.quality-report-aggregator.outputs.report }}"
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: process.env.REPORT
                })