name: reports

on: [pull_request]

jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
          - name: Quality Report
            id: quality-report
            uses: noh4nsen/quality-report@c59301ec282c896f74ac9f60405bfaef62d3eb25
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              head_branch: ${{ github.head_ref }}
              base_branch: ${{ github.base_ref }}