name: reports

on: [pull_request]

jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Go-diff
            id: go-diff
            uses: noh4nsen/go-diff@1.4.0
            with:
              head_branch: ${{ github.head_ref }}
              base_branch: ${{ github.base_ref }}
          - name: Checkout code
            uses: actions/checkout@v3
          - name: TFLint Report
            id: tflint-report
            uses: noh4nsen/tflint-report@0cb38987ac8c2c94039f2411bbd0abef040f901d
            with:
              modified_projects: ${{ steps.go-diff.outputs.modified_projects }}
          - name: Tfsec Report
            id: tfsec-report
            uses: noh4nsen/tfsec-report@2e2b041915d1c13d09062e28cf7f775753a119ef
            with:
              modified_projects: ${{ steps.go-diff.outputs.modified_projects }}
          - name: Checkov Report
            id: checkov-report
            uses: noh4nsen/checkov-report@7f0b542573e10a6e20fd78b37386a7637c36760e
            with:
              modified_projects: ${{ steps.go-diff.outputs.modified_projects }}
          - name: Quality Report Aggregator
            id: quality-report-aggregator
            uses: noh4nsen/quality-report-aggregator@73bfc790c331bb4cc1266feb1f6dcca46962abef
            with:
              tflint_report: ${{ steps.tflint-report.outputs.tflint_report }}
              tfsec_report: ${{ steps.tfsec-report.outputs.tfsec_report }}
              checkov_report: ${{ steps.checkov-report.outputs.checkov_report }}
          - name: print
            shell: bash
            run: |
              export report=${{ steps.quality-report-aggregator.outputs.report }}
              echo -e "$report"
          - name: Comment Report
            uses: actions/github-script@v6
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                const output = `\`${{ steps.quality-report-aggregator.outputs.report }}\``;

                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'teste'
                })