name: reports

on: [workflow_dispatch]

jobs:
    diff:
        runs-on: ubuntu-latest
        outputs:
            modified_projects: ${{ steps.go-diff.outputs.modified_projects }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Go-diff
            id: go-diff
            uses: noh4nsen/go-diff@1.4.0
            with:
              head_branch: POC-001
              base_branch: main

    tflint:
        runs-on: ubuntu-latest
        outputs:
            tflint_report: ${{ steps.tflint-report.outputs.tflint_report }}
        needs: [diff]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: TFLint Report
            id: tflint-report
            uses: noh4nsen/tflint-report@0.4.1
            with:
                modified_projects: ${{ needs.diff.outputs.modified_projects }}

    tfsec:
        runs-on: ubuntu-latest
        outputs:
            tfsec_report: ${{ steps.tfsec-report.outputs.tfsec_report }}
        needs: [diff]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Tfsec Report
            id: tfsec-report
            uses: noh4nsen/tfsec-report@0.3.1
            with:
                modified_projects: ${{ needs.diff.outputs.modified_projects }}

    checkov:
      runs-on: ubuntu-latest
      outputs:
          checkov_report: ${{ steps.checkov-report.outputs.checkov_report }}
      needs: [diff]
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Checkov Report
          id: checkov-report
          uses: noh4nsen/checkov-report@ef36c462b23c051ab1961f7da07d23ac1996e09f
          with:
              modified_projects: ${{ needs.diff.outputs.modified_projects }}

    print-report:
        runs-on: ubuntu-latest
        needs: [tflint, tfsec, checkov]
        steps:
          - name: print reports
            run: |
              echo "TFLINT REPORT:"
              echo "${{ fromJson(needs.tflint.outputs.tflint_report) }}"
              echo "TFSEC REPORT:"
              echo "${{ fromJson(needs.tfsec.outputs.tfsec_report) }}"
              echo "CHECKOV REPORT:"
              echo "${{ fromJson(needs.checkov.outputs.checkov_report) }}"