name: reports

on: [pull_request]

jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
          - name: Quality Report
            id: quality-report
            uses: noh4nsen/quality-report@b5b38eee81bc70c6ece6cb6e22ef81ed267ab469
            with:
              head_branch: ${{ github.head_ref }}
              base_branch: ${{ github.base_ref }}